"use client";

import { useState } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowUpRight, CalendarDays, Clock } from "lucide-react";
import Navigation from "@/components/Navigation";
import RegistrationDrawer from "@/components/RegistrationDrawer";

const events = [
  { type: "Ideathon", title: "Nirmith'26 Ideathon", description: "National-level Ideathon to bring together innovators from across India", date: "28th April 2025", time: "9:15 AM – 5:00 PM", prize: "₹50,000", image: "/images/team-group.png" },
  { type: "Hackathon", title: "Nirmith'26 Hackathon", description: "National-level execution-focused competition with Hardware & Software tracks", date: "28th April 2026", time: "5:00 PM onwards", prize: "₹1,00,000", image: "/images/award-ceremony.png", detail: "Hardware & Software" },
];

export default function EventsPage() {
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [selectedEvent, setSelectedEvent] = useState(events[0].title);
  const openRegistration = (title: string) => { setSelectedEvent(title); setDrawerOpen(true); };

  return <div className="min-h-screen bg-[#f5f2ec] text-[#1c1b1a]"><Navigation onOpenDrawer={() => openRegistration(events[0].title)} /><main>
    <section className="px-6 pb-24 pt-20 sm:pb-32 sm:pt-28"><div className="mx-auto max-w-7xl"><p className="text-sm text-stone-500">IoTronics events</p><div className="mt-10 grid gap-12 lg:grid-cols-12 lg:items-end"><h1 className="font-display text-[clamp(5.5rem,14vw,12rem)] leading-[0.73] tracking-[-0.065em] lg:col-span-8">Nirmith &apos;26</h1><p className="max-w-sm text-base leading-8 text-stone-600 lg:col-span-3 lg:col-start-10">Join us for an exciting lineup of hackathons and ideathons. Click on any event to learn more and register.</p></div></div></section>
    <section className="border-t border-stone-300/70 bg-[#ebe6de] px-6 py-20 sm:py-28"><div className="mx-auto max-w-7xl"><div className="space-y-20">{events.map((event, index) => <article key={event.type} className={`grid gap-10 lg:grid-cols-12 lg:items-center ${index === 1 ? "lg:pl-16" : ""}`}><div className={`relative aspect-[16/9] overflow-hidden lg:col-span-6 ${index === 1 ? "lg:order-2" : ""}`}><Image src={event.image} alt={event.title} fill sizes="(max-width: 1024px) 100vw, 50vw" className="object-cover" /><div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/65 to-transparent p-6 text-[#f5f2ec]"><p className="font-display text-4xl">Nirmith</p><p className="text-sm font-semibold">{event.type}</p><div className="mt-8 flex items-end justify-between text-sm"><span>{event.detail ?? ""}</span><span>Prize pool: {event.prize}</span></div></div></div><div className={`lg:col-span-5 ${index === 1 ? "lg:order-1" : "lg:col-start-8"}`}><p className="text-sm font-semibold text-[#c65b41]">{event.type}</p><h2 className="mt-3 font-display text-5xl leading-[0.9] tracking-[-0.04em] sm:text-6xl">{event.title}</h2><p className="mt-6 max-w-md leading-8 text-stone-600">{event.description}</p><div className="mt-8 flex flex-wrap gap-x-7 gap-y-3 border-y border-stone-400/60 py-4 text-sm text-stone-600"><span className="inline-flex items-center gap-2"><CalendarDays className="h-4 w-4" />{event.date}</span><span className="inline-flex items-center gap-2"><Clock className="h-4 w-4" />{event.time}</span></div><div className="mt-8 flex flex-wrap gap-5 text-sm font-semibold"><button onClick={() => openRegistration(event.title)} className="border-b border-[#1c1b1a] pb-2 hover:text-[#c65b41]">Know more</button><a href="https://unstop.com" target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 border-b border-[#1c1b1a] pb-2 hover:text-[#c65b41]">Unstop register <ArrowUpRight className="h-4 w-4" /></a></div></div></article>)}</div></div></section>
  </main><footer className="bg-[#1c1b1a] px-6 py-16 text-[#f5f2ec]"><div className="mx-auto grid max-w-7xl gap-12 md:grid-cols-2 lg:grid-cols-4"><div><p className="font-display text-5xl tracking-[-0.05em]">IoTronics</p><p className="mt-5 max-w-xs text-sm leading-7 text-stone-300">The premier IoT club dedicated to exploring the intersection of electronics, programming, and innovation.</p></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-stone-400">Quick links</p><div className="mt-5 grid gap-2 text-sm text-stone-200">{["Home", "About", "Projects", "Achievements", "Team", "Events", "Contact Us"].map((link) => <Link key={link} href={link === "Home" ? "/" : "/events"} className="hover:text-[#e78b68]">{link}</Link>)}</div></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-stone-400">Contact</p><div className="mt-5 space-y-2 text-sm leading-6 text-stone-200"><p>Room 302, F Block, EEE Dept, NMIT</p><a href="mailto:iotronics@nmit.ac.in" className="block hover:text-[#e78b68]">iotronics@nmit.ac.in</a><p>Rounak: +91 80058 63350<br />Rohit: +91 63549 59448</p></div></div><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-stone-400">Stay updated</p><p className="mt-5 text-sm leading-6 text-stone-300">Subscribe to get updates about events and projects.</p><form className="mt-5 flex border-b border-stone-500 pb-2"><input aria-label="Email address" type="email" placeholder="your@email.com" className="min-w-0 flex-1 bg-transparent text-sm outline-none placeholder:text-stone-500" /><button type="submit" className="text-sm font-semibold hover:text-[#e78b68]">Subscribe</button></form></div></div><div className="mx-auto mt-14 flex max-w-7xl flex-wrap justify-between gap-4 border-t border-stone-700 pt-6 text-xs text-stone-400"><div className="flex gap-4"><span>Privacy Policy</span><span>Terms of Service</span><span>Code of Conduct</span></div><span>Made with ♥ by IoTronics</span></div></footer><RegistrationDrawer isOpen={drawerOpen} onClose={() => setDrawerOpen(false)} defaultEvent={selectedEvent} /></div>;
}
